version: 2

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly
  skip-dirs:
    - examples
    - docs

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Detect unused code
    - misspell      # Spell checking
    - gosec         # Security issues
    - bodyclose     # HTTP response body close
    - noctx         # HTTP request without context
    - unconvert     # Unnecessary type conversions
    - whitespace    # Whitespace issues
  disable:
    - revive        # Style warnings - too noisy
    - prealloc      # Too strict for tests
    - unparam       # Too noisy for tests

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (os.Setenv)
      - (*Logger).Close
      - (*MultiLogger).Close

  govet:
    enable-all: true
    disable:
      - shadow       # Enabled separately
      - fieldalignment  # Too strict

  shadow:
    # Enable shadow checking
    strict: false

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude examples directory from all linters
    - path: examples/
      linters:
        - errcheck
        - gosec
        - revive
        - govet
        - staticcheck
        - unused

    # Exclude ALL linters from test files
    - path: _test\.go$
      linters:
        - errcheck
        - gosec
        - revive
        - govet
        - staticcheck
        - unused
        - ineffassign
        - misspell
        - bodyclose
        - noctx
        - unconvert
        - whitespace

    # Exclude duplicate imports warning (false positives)
    - linters:
        - typecheck
      text: "imported but not used"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
